# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a07de92cc1b6ebf990e4d91939ded53f62e5e12f776c027287c1e7bb2df359c46c4a2be79f1b7c17412c80136b3e6e9724cfd3d7bdcbf0f117116b237b95e778

test:
  secret_key_base: 1ea1c6620bde127d3680daf57640919e851a73827b6c6a5d69d936eaaa4c18396ebd8e6d4067cf36a1914335c8fdd2170c5feb27bd7d32af9dfd636a4a966f40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
